import os
from pathlib import Path

Import("env")


def load_dotenv(path: Path) -> dict:
    """Parse a simple KEY=VALUE .env file into a dict."""
    variables = {}
    if not path.exists():
        return variables
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            variables[key.strip()] = value.strip()
    return variables


# The PlatformIO project is at CTN App/CTN HARDWARE/CTN HARDWARE/
# so the repository root is two levels up from the project directory.
project_dir = Path(env.subst("$PROJECT_DIR"))
root_dir = project_dir.parent.parent
env_file = root_dir / ".env"

# Load .env, then let real environment variables override it.
dotenv_vars = load_dotenv(env_file)
merged = {**dotenv_vars, **os.environ}

# Required string values.
wifi_ssid = merged.get("WIFI_SSID", "")
wifi_password = merged.get("WIFI_PASSWORD", "")
supabase_url = merged.get("SUPABASE_URL", "")
supabase_api_key = merged.get("SUPABASE_API_KEY", merged.get("SUPABASE_ANON_KEY", ""))
supabase_table = merged.get("SUPABASE_TABLE", "sensor_readings")
device_id = merged.get("DEVICE_ID", "")
device_secret = merged.get("DEVICE_SECRET", "")
read_interval = merged.get("READ_INTERVAL", "15000")

missing = [k for k, v in {
    "WIFI_SSID": wifi_ssid,
    "WIFI_PASSWORD": wifi_password,
    "SUPABASE_URL": supabase_url,
    "SUPABASE_API_KEY": supabase_api_key,
    "DEVICE_ID": device_id,
    "DEVICE_SECRET": device_secret,
}.items() if not v]

if missing:
    raise SystemExit(
        "[load_env.py] Missing required environment variables: " + ", ".join(missing) +
        f". Please define them in {env_file} or in your shell environment."
    )

# Generate a C header so values become string literals without SCons quoting issues.
include_dir = project_dir / "include"
include_dir.mkdir(exist_ok=True)
secrets_file = include_dir / "secrets.h"

header_content = f"""/* Auto-generated by load_env.py — do not edit manually. */
#ifndef SECRETS_H
#define SECRETS_H

#define WIFI_SSID "{wifi_ssid}"
#define WIFI_PASSWORD "{wifi_password}"
#define SUPABASE_URL "{supabase_url}"
#define SUPABASE_API_KEY "{supabase_api_key}"
#define SUPABASE_TABLE "{supabase_table}"
#define DEVICE_ID "{device_id}"
#define DEVICE_SECRET "{device_secret}"
#define READ_INTERVAL {read_interval}

#endif /* SECRETS_H */
"""

with open(secrets_file, "w", encoding="utf-8") as f:
    f.write(header_content)

print(f"[load_env.py] Generated {secrets_file} from {env_file}")
